### ISSUE TITLE
IRFs P8R3_SOURCE_V2 can not be used in FT1.3.0, 1.7.1 and 1.9.3

### ISSUE THREAD

**Issue by phbruel** [fermi-lat/irfs#14] opened 2020-05-29 14:30 UTC
I'm currently testing FT 1.3.0 and I'm seeing a problem that is also in 1.7.1 and 1.9.3.

When I call gtexpcube2 with irfs=P8R3_SOURCE_V3, it works as expected:
(fermidev_1.3.0) rhel6-64c [07:25:35] ~/mynfspulsar/gtsrcmapsWeights/Results4FGLDR2/J0835-4510 > gtexpcube2 infile=out_gtltcube.fits cmap=none outfile=out_gtexpcube2_edisp_4FGL_test1.3.0.fits irfs=P8R3_SOURCE_V3 nxpix=300 nypix=300 binsz=0.2 coordsys=CEL xref=128.835876 yref=-45.176353 proj=STG ebinalg=LOG emin=63.095734 emax=316227.76600000 enumbins=37 axisrot=0 evtype=3 chatter=4
This is gtexpcube2 version HEAD
Using evtype=3 (i.e., FRONT/BACK irfs)
ResponseFunctions::load: IRF used: P8R3_SOURCE_V3
  event_types:  0  1
Computing binned exposure map..

When I call gtexpcube2 with irfs=P8R3_SOURCE_V2, it uses in fact V3:
(fermidev_1.3.0) rhel6-64c [07:27:21] ~/mynfspulsar/gtsrcmapsWeights/Results4FGLDR2/J0835-4510 > gtexpcube2 infile=out_gtltcube.fits cmap=none outfile=out_gtexpcube2_edisp_4FGL_test1.3.0.fits irfs=P8R3_SOURCE_V2 nxpix=300 nypix=300 binsz=0.2 coordsys=CEL xref=128.835876 yref=-45.176353 proj=STG ebinalg=LOG emin=63.095734 emax=316227.76600000 enumbins=37 axisrot=0 evtype=3 chatter=4
This is gtexpcube2 version HEAD
Using evtype=3 (i.e., FRONT/BACK irfs)
ResponseFunctions::load: IRF used: P8R3_SOURCE_V3
  event_types:  0  1
Computing binned exposure map..

**Comment by jasercion** [comment] 2020-06-05 20:56
@phbruel @donhorner I think I may have found the source of the issue.  Within the `caldb.indx` both the P8R3 V3 and P8R3 V2 irfs are being associated with the same generic class.  e.g.

`VERSION(P8R3_SOURCE_V3)` => `CLASS(P8R3_SOURCE_EDISP0)`
`VERSION(P8R3_SOURCE_V2)` => `CLASS(P8R3_SOURCE_EDISP0)`

This would also explain why the programs proceeded just fine despite changing the input irfs.  I'll work on getting these updated with version numbers.  Hopefully fixing this will resolve the issue.

**Comment by jasercion** [comment] 2020-07-23 13:55
I've isolated the function which is causing the issue.  It is specifically the index comparison in `Cuts::CALDB_implied_irfs()` that is throwing a false positive when checking the provided irf event class version against the CALDB.  Currently working on a fix.

**Comment by jasercion** [comment] 2020-07-23 16:05
@phbruel From what I can tell, forcing the latest version of an IRF pass/revision was a deliberate design choice made sometime in the past.  Within that function I mentioned in my last comment there is a specific conditional which overwrites the given version of the irf if there is a newer version of that Pass and Reprocessing available:

` if (pass_ver == m_pass_ver && (irfs_name == "" || candidate_irf_ver_num > irf_ver_num)) {
         irfs_name = it->first;
         irf_ver_num = candidate_irf_ver_num;`

My guess is that this was not noticed in the past because there is only one other valid set of irfs >= Pass 7 which have two different version string values (`P7REP`).  I ran a quick test and the behavior of the code is the same when requesting the `P7REP_*_V10` irfs: it automatically switches the selected irfs to `P7REP_*_V15`.

Since this was intentional behavior, I'd like to request some guidance on how you and the C&A group would like me to proceed with regards to updating this code.

**Comment by phbruel** [comment] 2020-07-28 13:35
Thanks Joe. The goal of being able to still use the P8R2_V2 IRFs is that one could finish an analysis started with these IRFs w/o having to rerun everything and still benefit from the improvement of the new Fermitools version. But, since P8R3_V3 IRFs are more correct, it seems to me that it is not crazy to force the user to switch to the new IRFs. Furthermore, it is possible to use the old version by setting a new CALDB directory in which the V3 files are a copy of the V2 files.

**Comment by jballet** [comment] 2020-07-28 14:53
I agree with Matthew that this behavior should not be silent if the user has asked a different set of irfs.
But I wonder what the advantage is to overrule the user's request. If the user does not know, he will have written CALDB. Changing irfs by hand can be very useful for tests.

**Comment by jasercion** [comment] 2020-07-28 18:30
My understanding based on the way the code seems to operate (which I totally admit may not be correct) is that the version number of the irfs should only be iterated if it is a bug fix or if the previous version is incorrect in some way.  New irfs or updates to a pass would be indicated by an iteration to the 'R' number.  If thought of this way, I could see the utility in forcing the user to use the latest _version_ of the same P & R to prevent them from obtaining incorrect results.

**Comment by jasercion** [comment] 2020-07-28 23:52
@phbruel I committed a change that includes a warning message if the user irf selection gets overwritten.  Can you please verify it behaves as expected in your tests?

`conda install -c conda-forge -c fermi -c fermi/label/dev fermitools=1.3.3`

You should see this message if you select an older version of an irf pass:

`WARNING:
Newer IRF version available. Updating IRF selection to: P8R3_SOURCE_V3
ResponseFunctions::load: IRF used: P8R3_SOURCE_V3 (PSF)`

Once this is confirmed I'll merge it into master and close the issue.

**Comment by jasercion** [comment] 2020-07-29 14:55
https://github.com/fermi-lat/dataSubselector/pull/5

**Comment by phbruel** [comment] 2020-08-04 11:17
I've just tested fermitools 1.3.4 and I see the warning message when trying to use the IRFs P8R3_SOURCE_V2.

**Comment by jballet** [comment] 2020-08-04 11:21
Bonjour Philippe,
Comment tu as fait pour installer cette version ?
Quand David lance le conda create il tourne sans jamais rien faire.
Nous avions fini par nous convaincre que c’était un problème chez eux, mais tu remets cette conclusion en question.
Quelle version de conda utilises-tu (David a 4.8.3) ?
Amicalement,
Jean

De : phbruel <notifications@github.com>
Envoyé : mardi 4 août 2020 13:17
À : fermi-lat/irfs <irfs@noreply.github.com>
Cc : Ballet Jean <jean.ballet@cea.fr>; Comment <comment@noreply.github.com>
Objet : Re: [fermi-lat/irfs] IRFs P8R3_SOURCE_V2 can not be used in FT1.3.0, 1.7.1 and 1.9.3 (#14)


I've just tested fermitools 1.3.4 and I see the warning message when trying to use the IRFs P8R3_SOURCE_V2.

**Comment by jasercion** [comment] 2020-08-05 16:02
@jballet What was the exact command David used in the installation attempt?  I'm unable to replicate the issue but this usually tends to arise when there is a channel mismatch during the dependency search.

**Comment by jballet** [comment] 2020-08-05 16:07
He tried giving a name to that version via -n fermi_1.3.4, but I think he also used -c fermi/label/dev instead of -c fermi/label/beta in the conda create command because dev appeared in Don's conda install command and David didn't pay attention that the two -c options (for conda install and conda create) differed.
On the whole I don't think there was any problem on your side.

**Comment by jasercion** [comment] 2020-08-10 15:59
Closing issue.  Can be reopened if we decide to change the behavior in the future.

**Closed as completed by jasercion** 2020-08-10 15:59 UTC

**Comment by jasercion** [comment] 2020-09-15 17:03
Check has been removed.  Tools should no longer override the user's IRF version choice as of dev versions 1.9.18 and 1.3.8

**Comment by donhorner** [comment] 2020-09-15 23:44
You can install the test version with commands like:
```
conda create -n fermi-1.3.8 -c conda-forge -c fermi/label/dev -c fermi fermitools=1.3.8
conda create -n fermi-1.9.18 -c conda-forge -c fermi/label/dev -c fermi fermitools=1.9.18
```
for the py2 and py3 versions, respectively.

**Comment by donhorner** [comment] 2020-09-17 18:17
We have new dev versions 1.3.9 and 1.9.18 that fixed an issue reported with the version check and gtdiffrsp.
